/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.LaboratorioMateriales;
import controllers.Laboratorios;
import controllers.Materiales;
import controllers.Prestamos;
import java.awt.BorderLayout;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.border.EmptyBorder;
import models.Devolucion;
import models.Laboratorio;
import models.LaboratorioMaterial;
import models.Material;
import models.Prestamo;
import utils.OracleUtils;

/**
 *
 * @author Ricardo
 */
public class Reporte extends javax.swing.JFrame {

    List<Prestamo> prestamos = (List<Prestamo>) Prestamos.select(OracleUtils.getDBConexion(), "select * from prestamo", Prestamo.class);
    List<Material> materiales = (List<Material>) Materiales.select(OracleUtils.getDBConexion(), "select * from material", Material.class);
    List<Laboratorio> laboratorios = (List<Laboratorio>) Laboratorios.select(OracleUtils.getDBConexion(), "select * from laboratorio", Laboratorio.class);
    
    
    /**
     * Creates new form Reporte
     */
    public Reporte() {
        
        setBounds(100, 100, 450, 300);
        PanelImagen p = new PanelImagen();
        p.setBorder(new EmptyBorder(5, 5, 5, 5));
        p.setLayout(new BorderLayout(0, 0));
        setContentPane(p);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        midPanel = new javax.swing.JPanel();
        lblResutl = new javax.swing.JLabel();
        botPanel = new javax.swing.JPanel();
        bttnConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte Prestamos");
        setResizable(false);

        topPanel.setOpaque(false);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Reporte Prestamos");
        lblTitulo.setToolTipText("");
        topPanel.add(lblTitulo);

        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);

        midPanel.setOpaque(false);
        midPanel.add(lblResutl);

        getContentPane().add(midPanel, java.awt.BorderLayout.CENTER);

        botPanel.setOpaque(false);

        bttnConsulta.setText("Consultar");
        bttnConsulta.setMaximumSize(new java.awt.Dimension(50, 23));
        bttnConsulta.setMinimumSize(new java.awt.Dimension(50, 23));
        bttnConsulta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bttnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnConsultaActionPerformed(evt);
            }
        });
        botPanel.add(bttnConsulta);

        getContentPane().add(botPanel, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnConsultaActionPerformed
        BigDecimal idPrestamo = (BigDecimal) prestamos;
        
    }//GEN-LAST:event_bttnConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botPanel;
    private javax.swing.JButton bttnConsulta;
    private javax.swing.JLabel lblResutl;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel midPanel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
