/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.Devoluciones;
import controllers.Laboratorios;
import controllers.Materiales;
import controllers.Prestamos;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import models.Laboratorio;
import models.Material;
import models.Prestamo;
import utils.OracleUtils;

/**
 *
 * @author Ricardo
 */
public class ReportePrestamo extends javax.swing.JFrame {

   static Connection cn;
 static Statement s;
 static ResultSet rs;

    /**
     * Creates new form Reporte
     */
    public ReportePrestamo() {

        setBounds(100, 100, 450, 300);
        PanelImagen p = new PanelImagen();
        p.setBorder(new EmptyBorder(5, 5, 5, 5));
        p.setLayout(new BorderLayout(0, 0));
        setContentPane(p);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrest = new javax.swing.JLabel();
        lblDevo = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        midPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResumen = new javax.swing.JTable();
        botPanel = new javax.swing.JPanel();
        bttnConsulta = new javax.swing.JButton();

        lblPrest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrest.setText("Id Prestamo");
        lblPrest.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblDevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDevo.setText("Id Devolucion");
        lblDevo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText("Status");
        lblStatus.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte Prestamos");
        setPreferredSize(new java.awt.Dimension(640, 480));
        setResizable(false);

        topPanel.setOpaque(false);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Reporte Prestamo");
        lblTitulo.setToolTipText("");
        topPanel.add(lblTitulo);

        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);

        midPanel.setEnabled(false);
        midPanel.setOpaque(false);

        tblResumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblResumen.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tblResumen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblResumen.setEnabled(false);
        tblResumen.setFocusable(false);
        tblResumen.setOpaque(false);
        jScrollPane1.setViewportView(tblResumen);

        midPanel.add(jScrollPane1);

        getContentPane().add(midPanel, java.awt.BorderLayout.CENTER);

        botPanel.setOpaque(false);

        bttnConsulta.setText("Consultar");
        bttnConsulta.setMaximumSize(new java.awt.Dimension(50, 23));
        bttnConsulta.setMinimumSize(new java.awt.Dimension(50, 23));
        bttnConsulta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bttnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnConsultaActionPerformed(evt);
            }
        });
        botPanel.add(bttnConsulta);

        getContentPane().add(botPanel, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnConsultaActionPerformed
try {
            //Para establecer el modelo al JTable
            DefaultTableModel modelo = new DefaultTableModel();
            this.tblResumen.setModel(modelo);
            //Para conectarnos a nuestra base de datos
            String url = "jdbc:oracle:thin:@localhost:1521:XE";
            // Establecemos los valores de cadena de conexión, usuario y contraseña
            cn = DriverManager.getConnection(url, "azinthehollow", "1337");
            //Para ejecutar la consulta
            s = cn.createStatement();
            //Ejecutamos la consulta y los datos lo almacenamos en un ResultSet
             rs = s.executeQuery("select * from prestamo");
            //Obteniendo la informacion de las columnas que estan siendo consultadas
            ResultSetMetaData rsMd = rs.getMetaData();
            //La cantidad de columnas que tiene la consulta
            int cantidadColumnas = rsMd.getColumnCount();
            //Establecer como cabezeras el nombre de las colimnas
            for (int i = 1; i <= cantidadColumnas; i++) {
             modelo.addColumn(rsMd.getColumnLabel(i));
            }
            //Creando las filas para el JTable
            while (rs.next()) {
             Object[] fila = new Object[cantidadColumnas];
             for (int i = 0; i < cantidadColumnas; i++) {
               fila[i]=rs.getObject(i+1);
             }
             modelo.addRow(fila);
            }
            rs.close();
            cn.close();
       } catch (Exception ex) {
        ex.printStackTrace();
       }



    }//GEN-LAST:event_bttnConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportePrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportePrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportePrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportePrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportePrestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botPanel;
    private javax.swing.JButton bttnConsulta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDevo;
    private javax.swing.JLabel lblPrest;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel midPanel;
    private javax.swing.JTable tblResumen;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
